### ISSUE TITLE
Freddy vs Freddie

### ISSUE THREAD

**Issue by jefftmarks** [learn-co-curriculum/phase-3-nested-hash-iteration#10]
### Canvas Link

https://learning.flatironschool.com/courses/5215/pages/enumerables-iterating-over-nested-hashes?module_item_id=469900

### Concern

In canvas, it's spelled Freddie Mercury. But in the ruby file, it's spelled Freddy Mercury. Made it difficult to debug when I was copying the code to try myself

**Comment by jlboba** [comment]
Hello, and thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not!
We appreciate your support! 💙
