### ISSUE TITLE
Tests need to be updated

### ISSUE THREAD

**Issue by martinezjf2** [learn-co-curriculum/phase-3-nested-hash-iteration#13]
### Canvas Link

https://learning.flatironschool.com/courses/5643/pages/enumerables-iterating-over-nested-hashes?module_item_id=448816

### Concern

the contacts-spec should be updated to look for "Freddie" instead of "Freddy". Students don't pass the test because the tests and the given code do not align

### Additional Context

readme is fine, the initial code is fine, just tests needs to be readjusted 

### Suggested Changes

fix the tests

**Comment by lizbur10** [comment]
Thanks @martinezjf2 ! This should now be fixed 💙
